import type { DataSourceSummary } from '@/api/browser'

const dataSourceUiFixtureParameter = 'uiFixture'
const dataSourceUiFixtureValue = 'data-sources'

// 开发样本只承载列表安全摘要字段；用户名均为合成值，不包含密码、令牌或可连接的真实地址。
export const DATA_SOURCE_UI_FIXTURES: readonly DataSourceSummary[] = [
  {
    id: 'ui-fixture-data-source-01',
    displayName: '开发源',
    environment: 'DEVELOPMENT',
    connectionKind: 'ODP',
    compatibilityMode: 'MYSQL',
    host: '192.0.2.10',
    port: 2881,
    clusterName: 'fixture-dev-a',
    tenantName: 'app',
    username: 'app_user',
    sysCredentialState: 'AVAILABLE',
    defaultDatabase: 'fixture_orders',
    state: 'ENABLED',
    revision: 101,
    credentialRevision: 201,
    lastTestStatus: 'INVALIDATED',
    lastTestedAt: '2026-01-02T03:04:05.000Z',
  },
  {
    id: 'ui-fixture-data-source-02',
    displayName: '超长中文数据源名称用于验证数据源管理表格在窄屏和宽屏下的截断显示悬浮提示排序筛选以及操作列对齐稳定性',
    environment: 'TEST',
    connectionKind: 'ODP',
    compatibilityMode: 'ORACLE',
    host: 'odp-router.test',
    port: 2883,
    clusterName: 'fixture-integration-cluster',
    tenantName: 'tenant08',
    username: 'report_ro',
    sysCredentialState: 'UNAVAILABLE',
    state: 'DISABLED',
    revision: 102,
    credentialRevision: 202,
    lastTestStatus: 'FAILED',
    lastTestedAt: '2026-01-03T04:05:06.000Z',
  },
  {
    id: 'ui-fixture-data-source-03',
    displayName: 'dev-mysql',
    environment: 'DEVELOPMENT',
    connectionKind: 'ODP',
    compatibilityMode: 'MYSQL',
    host: '198.51.100.20',
    port: 2882,
    clusterName: 'fixture-dev-b',
    tenantName: 't1',
    username: 'root',
    sysCredentialState: 'AVAILABLE',
    defaultDatabase: 'fixture_catalog',
    state: 'ENABLED',
    revision: 103,
    credentialRevision: 203,
    lastTestStatus: 'SUCCEEDED',
    lastTestedAt: '2026-01-04T05:06:07.000Z',
  },
  {
    id: 'ui-fixture-data-source-04',
    displayName: 'production-analytics-replica-with-an-intentionally-very-long-english-data-source-name-for-overflow-validation',
    environment: 'PRODUCTION',
    connectionKind: 'ODP',
    compatibilityMode: 'ORACLE',
    host: 'oracle-db.test',
    port: 2884,
    clusterName: 'fixture-production-analytics',
    tenantName: 'prod-rpt',
    username: 'analytics',
    sysCredentialState: 'AVAILABLE',
    state: 'DISABLED',
    revision: 104,
    credentialRevision: 204,
    lastTestStatus: 'INVALIDATED',
    lastTestedAt: '2026-01-05T06:07:08.000Z',
  },
  {
    id: 'ui-fixture-data-source-05',
    displayName: '测试-未测试',
    environment: 'TEST',
    connectionKind: 'ODP',
    compatibilityMode: 'MYSQL',
    host: '203.0.113.30',
    port: 2883,
    clusterName: 'fixture-test-a',
    tenantName: 'qa',
    username: 'qa_user',
    sysCredentialState: 'UNAVAILABLE',
    defaultDatabase: 'fixture_qa',
    state: 'ENABLED',
    revision: 105,
    credentialRevision: 205,
  },
  {
    id: 'ui-fixture-data-source-06',
    displayName: 'staging-oracle-failed',
    environment: 'STAGING',
    connectionKind: 'ODP',
    compatibilityMode: 'ORACLE',
    host: 'stage-db.test',
    port: 2881,
    clusterName: 'fixture-staging-a',
    tenantName: 'stage',
    username: 'oracle',
    sysCredentialState: 'AVAILABLE',
    state: 'DISABLED',
    revision: 106,
    credentialRevision: 206,
    lastTestStatus: 'FAILED',
    lastTestedAt: '2026-01-06T07:08:09.000Z',
  },
  {
    id: 'ui-fixture-data-source-07',
    displayName: '生产订单主库',
    environment: 'PRODUCTION',
    connectionKind: 'ODP',
    compatibilityMode: 'MYSQL',
    host: '192.0.2.70',
    port: 2883,
    clusterName: 'fixture-production-orders',
    tenantName: 'orders',
    username: 'orders',
    sysCredentialState: 'UNAVAILABLE',
    defaultDatabase: 'fixture_orders',
    state: 'ENABLED',
    revision: 107,
    credentialRevision: 207,
    lastTestStatus: 'SUCCEEDED',
    lastTestedAt: '2026-01-07T08:09:10.000Z',
  },
  {
    id: 'ui-fixture-data-source-08',
    displayName: 'dev-disabled-untested',
    environment: 'DEVELOPMENT',
    connectionKind: 'ODP',
    compatibilityMode: 'ORACLE',
    host: 'dev-router.test',
    port: 2884,
    clusterName: 'fixture-dev-c',
    tenantName: 'dev',
    username: 'dev_user',
    sysCredentialState: 'UNAVAILABLE',
    state: 'DISABLED',
    revision: 108,
    credentialRevision: 208,
  },
  {
    id: 'ui-fixture-data-source-09',
    displayName: '预生产-连接已失效',
    environment: 'STAGING',
    connectionKind: 'ODP',
    compatibilityMode: 'MYSQL',
    host: '198.51.100.90',
    port: 2882,
    clusterName: 'fixture-staging-b',
    tenantName: 'release',
    username: 'release',
    sysCredentialState: 'AVAILABLE',
    defaultDatabase: 'fixture_release',
    state: 'ENABLED',
    revision: 109,
    credentialRevision: 209,
    lastTestStatus: 'INVALIDATED',
    lastTestedAt: '2026-01-08T09:10:11.000Z',
  },
  {
    id: 'ui-fixture-data-source-10',
    displayName: 'qa',
    environment: 'TEST',
    connectionKind: 'ODP',
    compatibilityMode: 'ORACLE',
    host: 'db.test',
    port: 2881,
    clusterName: 'fixture-test-b',
    tenantName: 'q',
    username: 'q',
    sysCredentialState: 'UNAVAILABLE',
    state: 'DISABLED',
    revision: 110,
    credentialRevision: 210,
    lastTestStatus: 'SUCCEEDED',
    lastTestedAt: '2026-01-09T10:11:12.000Z',
  },
  {
    id: 'ui-fixture-data-source-11',
    displayName: 'reporting-readonly',
    environment: 'PRODUCTION',
    connectionKind: 'ODP',
    compatibilityMode: 'MYSQL',
    host: '203.0.113.110',
    port: 2883,
    clusterName: 'fixture-production-reporting',
    tenantName: 'reports',
    username: 'reporter',
    sysCredentialState: 'AVAILABLE',
    defaultDatabase: 'fixture_reports',
    state: 'ENABLED',
    revision: 111,
    credentialRevision: 211,
    lastTestStatus: 'FAILED',
    lastTestedAt: '2026-01-10T11:12:13.000Z',
  },
  {
    id: 'ui-fixture-data-source-12',
    displayName: '中文English混排数据源-UI-fixture',
    environment: 'DEVELOPMENT',
    connectionKind: 'ODP',
    compatibilityMode: 'ORACLE',
    host: 'mixed.test',
    port: 2884,
    clusterName: 'fixture-dev-d',
    tenantName: 'mixed',
    username: 'mixed_user',
    sysCredentialState: 'UNAVAILABLE',
    state: 'DISABLED',
    revision: 112,
    credentialRevision: 212,
  },
  {
    id: 'ui-fixture-data-source-13',
    displayName: 'tenant-short',
    environment: 'STAGING',
    connectionKind: 'ODP',
    compatibilityMode: 'MYSQL',
    host: '192.0.2.130',
    port: 2881,
    clusterName: 'fixture-staging-c',
    tenantName: 'x',
    username: 'tenant',
    sysCredentialState: 'AVAILABLE',
    defaultDatabase: 'fixture_tenant',
    state: 'ENABLED',
    revision: 113,
    credentialRevision: 213,
    lastTestStatus: 'SUCCEEDED',
    lastTestedAt: '2026-01-11T12:13:14.000Z',
  },
  {
    id: 'ui-fixture-data-source-14',
    displayName: '长租户演示',
    environment: 'TEST',
    connectionKind: 'ODP',
    compatibilityMode: 'ORACLE',
    host: 'tenant-db.test',
    port: 2882,
    clusterName: 'fixture-test-c',
    tenantName: 'tenant14',
    username: 'audit',
    sysCredentialState: 'UNAVAILABLE',
    state: 'DISABLED',
    revision: 114,
    credentialRevision: 214,
    lastTestStatus: 'INVALIDATED',
    lastTestedAt: '2026-01-12T13:14:15.000Z',
  },
  {
    id: 'ui-fixture-data-source-15',
    displayName: 'edge',
    environment: 'PRODUCTION',
    connectionKind: 'ODP',
    compatibilityMode: 'MYSQL',
    host: '198.51.100.150',
    port: 2883,
    clusterName: 'fixture-production-edge',
    tenantName: 'edge',
    username: 'edge_user',
    sysCredentialState: 'AVAILABLE',
    defaultDatabase: 'fixture_edge',
    state: 'ENABLED',
    revision: 115,
    credentialRevision: 215,
    lastTestStatus: 'FAILED',
    lastTestedAt: '2026-01-13T14:15:16.000Z',
  },
  {
    id: 'ui-fixture-data-source-16',
    displayName: '回归验证专用数据源',
    environment: 'STAGING',
    connectionKind: 'ODP',
    compatibilityMode: 'ORACLE',
    host: 'odp.test',
    port: 2884,
    clusterName: 'fixture-staging-d',
    tenantName: 'regress',
    username: 'regress',
    sysCredentialState: 'UNAVAILABLE',
    state: 'DISABLED',
    revision: 116,
    credentialRevision: 216,
  },
]

// 双重开关必须同时满足；重复参数也按歧义输入失败关闭，避免意外进入演示状态。
export function isDataSourceUiFixtureEnabled(search: string, isDevelopment: boolean): boolean {
  if (!isDevelopment) return false
  const values = new URLSearchParams(search).getAll(dataSourceUiFixtureParameter)
  return values.length === 1 && values[0] === dataSourceUiFixtureValue
}

// 每次返回副本，避免页面内的临时操作污染固定样本或后续加载结果。
export function dataSourceUiFixtureForSearch(search: string, isDevelopment = import.meta.env.DEV): DataSourceSummary[] | undefined {
  if (!isDataSourceUiFixtureEnabled(search, isDevelopment)) return undefined
  return DATA_SOURCE_UI_FIXTURES.map((source): DataSourceSummary => ({ ...source }))
}
