<script setup lang="ts">
import { computed } from 'vue'
import { useRoute } from 'vue-router'

import WizardFrame from '@/components/WizardFrame.vue'

const route = useRoute()
const activeStep = computed(() => {
  const value = Number(route.query.step ?? '1')
  return Number.isInteger(value) && value >= 1 && value <= 6 ? value : 1
})
const titles = ['选择数据源', '文件来源', '内容与格式', '对象与映射', '执行参数', '预检查与命令']
</script>

<template>
  <section class="page-heading"><div><h1>新建普通导入任务</h1><p>OBLOADER 普通导入与旁路导入是两条独立流程；本向导不会生成 <code>--direct</code>、<code>--rpc-port</code> 或 <code>--parallel</code>。</p></div><span class="draft-status">草稿尚未创建</span></section>
  <WizardFrame kind="normal" :active-step="activeStep">
    <template #default>
      <section v-if="activeStep === 1" class="form-section"><h2>选择已有数据源</h2><p>目标数据源和默认数据库来自已登记的 ODP 连接；向导不重复编辑连接信息或凭据。</p><div class="placeholder-control"><span>已授权且完成基础连接测试的数据源将在功能接入后加载</span></div></section>
      <section v-else-if="activeStep === 2" class="form-section"><h2>文件来源与初步发现</h2><div class="section-block"><h3>输入位置</h3><div class="radio-row"><label><input checked type="radio" name="source" />执行节点本地绝对路径</label><label><input disabled type="radio" name="source" />官方支持的远程存储（待安全凭据设计）</label></div><label class="field-label wide-label">文件或目录路径 <b>*</b><input placeholder="由执行节点读取的完整绝对路径" /></label><p class="section-hint">不提供浏览器上传、任意 URI、平台文件管理或文件内容编辑。</p></div><div class="section-block"><h3>初步文件发现</h3><div class="placeholder-control short"><span>仅在节点可达后展示路径可读性、按后缀分组的有限样例；不读取业务内容推断字段。</span></div></div><details class="parameter-fold"><summary>高级文件条件 <span>文件正则、编码、第三方文件和临时目录按适用条件显示</span></summary><p>第 3 步确定内容与格式后，系统重新计算有效文件集；当前发现结果不代表可以导入。</p></details></section>
      <section v-else-if="activeStep === 3" class="form-section"><h2>导入内容与格式</h2><div class="option-grid"><label class="option-card"><input type="radio" name="content" />仅对象定义<span>仅导入对象结构和对象元数据。</span></label><label class="option-card"><input type="radio" name="content" />仅数据<span>需要选择一种数据格式。</span></label><label class="option-card selected"><input checked type="radio" name="content" />对象定义和数据<span>DDL 与数据文件分别处理。</span></label><label class="option-card"><input type="radio" name="content" />MIX 混合文件<span>独立解析模式；与 DDL 和其他格式互斥。</span></label></div><h3 class="subheading">数据格式</h3><div class="format-grid"><label class="format-card selected"><input checked type="radio" name="format" />CSV</label><label class="format-card"><input type="radio" name="format" />Insert SQL</label><label class="format-card"><input type="radio" name="format" />CUT</label><label class="format-card"><input type="radio" name="format" />POS<span>必须提供控制文件。</span></label><label class="format-card"><input type="radio" name="format" />ORC</label><label class="format-card"><input type="radio" name="format" />Parquet</label><label class="format-card"><input type="radio" name="format" />Avro<span>不支持 Complex Types。</span></label></div><p class="section-hint">只显示当前格式的活动字段；压缩表示读取 OBDUMPER 压缩输入，不是再次压缩导入数据。</p></section>
      <section v-else-if="activeStep === 4" class="form-section"><h2>目标对象与文件映射</h2><div class="option-grid"><label class="option-card selected"><input checked type="radio" name="target" />全部对象<span><code>--all</code> 与具体对象参数严格互斥。</span></label><label class="option-card"><input type="radio" name="target" />指定对象<span>至少包含一种适用对象表达式。</span></label></div><div class="section-block"><h3>列映射方式</h3><div class="option-grid"><label class="option-card selected"><input checked type="radio" name="mapping" />按文件列顺序<span>不提供平台智能字段映射。</span></label><label class="option-card"><input type="radio" name="mapping" />控制文件<span>POS 必填；与自动映射互斥。</span></label><label class="option-card"><input type="radio" name="mapping" />官方自动列映射<span>仅 CSV / ORC / Parquet。</span></label><label class="option-card"><input type="radio" name="mapping" />显式列名单<span>按官方字段承载，不做表达式编辑器。</span></label></div></div><p class="section-hint">映射预览只展示由文件头/元数据和目标元数据形成的只读准备结果；最终在预检查中验证。</p></section>
      <section v-else-if="activeStep === 5" class="form-section"><h2>执行参数与高风险操作</h2><div class="parameter-list"><div><strong>错误与重复数据</strong><span><code>max-discards</code>、<code>max-errors</code>、<code>strict</code> 均独立表达</span><input disabled placeholder="沿用官方默认" /></div><div><strong>性能与资源</strong><span>线程、批次、分块、限速与 JVM 内存不提供伪精确推荐</span><input disabled placeholder="沿用官方默认" /></div><div><strong>执行节点</strong><span>真实节点可用性和资源由任务预检查确认</span><input disabled placeholder="尚未选择" /></div></div><details class="parameter-fold"><summary>高级配置 <span>所有已确认普通导入参数可按分类找到</span></summary><p>折叠不是删除；未显式设置的字段沿用官方默认，不为命令长度主动写出。</p></details><details class="parameter-fold"><summary>专家配置 <span>只开放已映射字段，并受权限和条件约束</span></summary><p><code>replace-data</code>、<code>replace-object</code>、<code>truncate-table</code>、<code>delete-from-table</code>只在适用条件下显示。truncate 与 delete 严格互斥；<code>--yes</code>只由平台在等价确认后派生。</p></details></section>
      <section v-else class="form-section"><h2>预检查与完整命令</h2><section class="precheck-list"><h3>预检查结果</h3><div v-for="item in ['数据源与权限', '执行节点与工具', '文件集合', '内容与格式', '对象与列映射', '参数约束', '高风险确认']" :key="item" class="precheck-item"><span class="status-dot neutral" /><strong>{{ item }}</strong><span>尚未执行；当前页面不会把未知事实显示为通过。</span></div></section><section class="command-empty"><div><h3>完整命令（脱敏）</h3><button type="button" class="button button-secondary" disabled>复制脱敏命令</button></div><pre><code>完成普通导入配置和 Agent 预检查后，由控制面生成只读、脱敏的 OBLOADER 命令。</code></pre><p>普通导入不会生成旁路导入专属参数。</p></section></section>
    </template>
    <template #summary><h2>配置总览</h2><dl class="summary-definition"><div><dt>当前步骤</dt><dd>{{ titles[activeStep - 1] }}</dd></div><div><dt>数据源</dt><dd>尚未选择</dd></div><div><dt>文件来源</dt><dd>尚未配置</dd></div><div><dt>内容与格式</dt><dd>尚未配置</dd></div><div><dt>对象与映射</dt><dd>尚未配置</dd></div><div><dt>预检查</dt><dd>尚未执行</dd></div></dl><p class="aside-note">失败任务只有存在有效 <code>load.ckpt</code>、原路径和不可变快照匹配时，才可能显示从检查点继续。</p></template>
  </WizardFrame>
</template>
