// 唯一视觉值源：冻结值来自 P0 §9 和 Data Sources P1，不从组件默认值反推产品决策。
export const foundation = {
  white: '#ffffff',
  blue: '#0b6bff',
  blueHover: '#3385ff',
  blueActive: '#0057d9',
  blueSoft: '#eaf3ff',
  blueSubtle: '#f4f8ff',
  linkBlue: '#0b6bff',
  ink: '#132039',
  secondary: '#5f6b7a',
  formInk: '#132039',
  formSecondary: '#5f6b7a',
  muted: '#8a94a3',
  disabled: '#a8b3c2',
  page: '#f3f6fc',
  navigation: '#f7f9fd',
  subtle: '#f8fafd',
  selected: '#edf4ff',
  border: '#e5eaf2',
  borderStrong: '#d8e0eb',
  rowBorder: '#e5eaf2',
  headerBorder: '#d8e0eb',
  headerDivider: '#e5eaf2',
  navDivider: '#e5eaf2',
  rowAlternate: '#f8fafd',
  rowHover: '#f7fafc',
  success: '#16a34a',
  successDot: '#16a34a',
  successSurface: '#f0fdf4',
  successBorder: '#bbf7d0',
  warning: '#d97706',
  warningSurface: '#fffbeb',
  warningBorder: '#fde68a',
  danger: '#dc2626',
  dangerHover: '#b91c1c',
  dangerSurface: '#fef2f2',
  dangerBorder: '#fecaca',
  mask: 'rgb(19 32 57 / 32%)',
  surfaceShadow: '0 1px 2px rgb(31 45 61 / 3%), 0 4px 12px rgb(31 45 61 / 3.5%)',
  overlayShadow: '0 12px 28px rgb(31 45 61 / 12%)',
  drawerShadow: '-12px 0 28px rgb(31 45 61 / 12%)',
  fontUI: '"Noto Sans SC", "PingFang SC", "Microsoft YaHei", system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
  fontMono: '"JetBrains Mono", "Cascadia Mono", Consolas, "SFMono-Regular", ui-monospace, monospace',
  space: { 1: 4, 2: 8, 3: 12, 4: 16, 6: 24, 8: 32 },
} as const

export const semantic = {
  surface: foundation.white,
  page: foundation.page,
  subtle: foundation.subtle,
  text: foundation.ink,
  secondary: foundation.secondary,
  formText: foundation.formInk,
  formSecondary: foundation.formSecondary,
  muted: foundation.muted,
  disabled: foundation.disabled,
  border: foundation.border,
  borderStrong: foundation.borderStrong,
  primary: foundation.blue,
  primaryHover: foundation.blueHover,
  primaryActive: foundation.blueActive,
  primarySoft: foundation.blueSoft,
  primarySubtle: foundation.blueSubtle,
  link: foundation.linkBlue,
  selected: foundation.selected,
  success: foundation.success,
  warning: foundation.warning,
  danger: foundation.danger,
  neutral: foundation.secondary,
} as const

export const component = {
  control: { height: 36, radius: 4, managementRadius: 6, fontSize: 14, lineHeight: 22 },
  table: { headerHeight: 36, rowHeight: 42, paddingBlock: 7, paddingInline: 16, radius: 8, metadataSize: 12, metadataLineHeight: 20 },
  action: { iconSize: 32, overlayIconSize: 32, confirmHeight: 36 },
  field: { labelSize: 13, labelLineHeight: 20, helperSize: 12, helperLineHeight: 18 },
  overlay: { radius: 8, drawerRadius: 0, titleSize: 17, titleLineHeight: 24, confirmWidth: 552 },
  focus: { width: 2, offset: 2 },
  motion: { feedbackMs: 200 },
  availability: { width: 44, height: 22, handleSize: 18, inset: 2 },
} as const

export const product = {
  shell: { navigationWidth: 200, collapsedWidth: 48, headerHeight: 48, workspacePadding: 24, brandSize: 18 },
  navigation: { background: foundation.navigation, text: '#334155', icon: '#6b778c', hover: foundation.blueSubtle },
  task: { railWidth: 208, compactRailWidth: 176 },
  source: { editorWidth: 520, tableMinimumWidth: 850 },
  inspector: { width: 640 },
  typography: { titleSize: 24, titleLineHeight: 32, sectionSize: 16, weight: 600 },
  environment: {
    DEVELOPMENT: { color: '#389e0d', background: '#f6ffed' },
    TEST: { color: '#d48806', background: '#fffbe6' },
    STAGING: { color: '#8a5a00', background: '#fff7df' },
    PRODUCTION: { color: '#b42318', background: '#fef2f2' },
  },
} as const
