import { expect, test } from '@playwright/test'
import { DATA_SOURCE_UI_FIXTURES } from '../src/workbench/sources/dataSourceUiFixture'

test('新建环境从默认提示中显式选择，预生产存量仍可编辑', async ({ page }) => {
  await page.route('**/api/v1/**', route => route.abort())
  await page.goto('/data-sources?uiFixture=data-sources')
  await page.getByRole('button', { name: '新建数据源', exact: true }).click()
  await page.getByRole('menuitem', { name: 'OceanBase MySQL', exact: true }).click()
  const drawer = page.getByRole('dialog', { name: '新建数据源', exact: true })
  await expect(drawer.locator('.orch-source-metadata .ant-select-selection-placeholder')).toHaveText('默认')
  await drawer.getByRole('button', { name: '确定', exact: true }).click()
  await expect(drawer.getByText('请选择环境。', { exact: true })).toBeVisible()
  await drawer.locator('.orch-source-metadata .ant-select-selector').click()
  const options = page.locator('.ant-select-dropdown:visible .ant-select-item-option')
  await expect(options).toHaveText(['默认', '开发', '生产', '测试'])
  await expect(options.first()).toHaveClass(/ant-select-item-option-disabled/)
  await options.nth(1).click()
  await expect(drawer.locator('.orch-source-metadata .ant-select-selection-item')).toContainText('开发')
  await expect(drawer.getByText('请选择环境。', { exact: true })).toHaveCount(0)

  await page.goto('/data-sources?uiFixture=data-sources')
  await page.getByRole('button', { name: 'Internal reporting db', exact: true }).click()
  const legacyDrawer = page.getByRole('dialog', { name: '编辑数据源', exact: true })
  await expect(legacyDrawer.locator('.orch-source-metadata .ant-select-selection-item')).toContainText('预生产')
  await legacyDrawer.locator('.orch-source-metadata .ant-select-selector').click()
  await expect(page.locator('.ant-select-dropdown:visible .ant-select-item-option').last()).toHaveText('预生产')
})

test('状态切换只更新行内状态，环境标签保留浅色底', async ({ page }) => {
  await page.route('**/api/v1/**', route => route.abort())
  await page.goto('/data-sources?uiFixture=data-sources')
  const availability = page.getByRole('switch', { name: 'Production finance reporting 的可用状态' })
  await availability.click()
  await expect(availability).not.toBeChecked()
  await expect(page.locator('.ant-message')).toHaveCount(0)
  await expect(page.getByLabel('正在处理数据源操作')).toHaveCount(0)
  const production = page.locator('.ant-tag').filter({ hasText: '生产' }).first()
  await expect(production).toBeVisible()
  expect(await production.evaluate(el => getComputedStyle(el).color)).toBe('rgb(180, 35, 24)')
  expect(await production.evaluate(el => getComputedStyle(el).backgroundColor)).toBe('rgb(254, 242, 242)')
  await expect(page.locator('.orch-identity-cell .anticon')).toHaveCount(0)
  const heading = page.getByRole('columnheader', { name: '数据源', exact: true })
  const name = page.getByRole('button', { name: 'Production finance reporting', exact: true })
  const contentLeft = await heading.evaluate(el => el.getBoundingClientRect().left + parseFloat(getComputedStyle(el).paddingLeft))
  const nameLeft = await name.evaluate(el => el.getBoundingClientRect().left + parseFloat(getComputedStyle(el).paddingLeft) + parseFloat(getComputedStyle(el).borderLeftWidth))
  expect(Math.abs(nameLeft - contentLeft)).toBeLessThanOrEqual(1)
})

test('编辑数据源抽屉在低视口可滚动且名称字段独立成行', async ({ page }, info) => {
  await page.setViewportSize({ width: 1280, height: 720 })
  await page.route('**/api/v1/**', route => route.abort())
  await page.goto('/data-sources?uiFixture=data-sources')
  await page.getByRole('button', { name: 'Production finance reporting', exact: true }).click()
  const drawer = page.getByRole('dialog', { name: '编辑数据源', exact: true })
  await expect(drawer).toBeVisible()
  const scrollable = drawer.locator('.orch-editor-scroll')
  await expect(scrollable).toBeVisible()
  await expect(drawer.getByLabel('数据源名称', { exact: true })).toHaveValue('Production finance reporting')
  const metrics = await scrollable.evaluate((element) => ({
    clientHeight: element.clientHeight,
    scrollHeight: element.scrollHeight,
  }))
  expect(metrics.scrollHeight).toBeGreaterThan(metrics.clientHeight + 80)
  await scrollable.evaluate((element) => { element.scrollTop = element.scrollHeight })
  await expect(drawer.getByRole('button', { name: /高级设置/ })).toBeInViewport()
  await scrollable.evaluate((element) => { element.scrollTop = 0 })
  const nameItem = drawer.getByLabel('数据源名称', { exact: true }).locator('xpath=ancestor::*[contains(@class,"ant-form-item")][1]')
  const nameBox = await nameItem.boundingBox()
  const inputBox = await drawer.getByLabel('数据源名称', { exact: true }).boundingBox()
  expect(nameBox!.width).toBeGreaterThan(400)
  expect(inputBox!.width).toBeGreaterThan(360)
  await page.screenshot({ path: info.outputPath('source-editor-layout.png'), fullPage: false })
  await page.setViewportSize({ width: 390, height: 844 })
  const mobileDrawer = await drawer.boundingBox()
  const mobileHost = await drawer.getByLabel('主机 IP/域名', { exact: true }).boundingBox()
  expect(mobileDrawer!.x).toBeGreaterThanOrEqual(0)
  expect(mobileDrawer!.width).toBeLessThanOrEqual(390)
  expect(mobileHost!.x).toBeGreaterThanOrEqual(0)
  expect(mobileHost!.x + mobileHost!.width).toBeLessThanOrEqual(390)
  await drawer.getByRole('button', { name: '测试连接', exact: true }).click()
  const nodeSelect = await drawer.locator('.orch-inline-test-controls .ant-select').boundingBox()
  const refresh = await drawer.getByRole('button', { name: '刷新可测试节点' }).boundingBox()
  const start = await drawer.getByRole('button', { name: '开始测试', exact: true }).boundingBox()
  expect(Math.abs((nodeSelect!.y + nodeSelect!.height / 2) - (refresh!.y + refresh!.height / 2))).toBeLessThanOrEqual(4)
  expect(start!.y).toBeGreaterThanOrEqual(nodeSelect!.y + nodeSelect!.height)
  expect(start!.x + start!.width).toBeLessThanOrEqual(mobileDrawer!.x + mobileDrawer!.width)
})

test('高级设置键盘展开、收起后的错误定位与空态恢复', async ({ page }) => {
  const errors: string[] = []
  let stage = '筛选空态'
  page.on('pageerror', error => errors.push(`${stage}: ${error.message}`))
  await page.route('**/api/v1/**', route => route.abort())
  await page.goto('/data-sources?uiFixture=data-sources')
  await page.getByRole('textbox', { name: '搜索数据源' }).fill('no-synthetic-match')
  await expect(page.getByText('未找到匹配的数据源', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '清除筛选', exact: true }).last().click()
  await expect(page.getByRole('textbox', { name: '搜索数据源' })).toBeFocused()
  stage = '打开抽屉'
  await page.getByRole('button', { name: '新建数据源', exact: true }).click()
  await page.getByRole('menuitem', { name: 'OceanBase MySQL', exact: true }).click()
  const drawer = page.getByRole('dialog', { name: '新建数据源', exact: true })
  const advanced = drawer.getByRole('button', { name: /高级设置/ })
  stage = '展开高级设置'
  await advanced.focus()
  await page.keyboard.press('Enter')
  await expect(advanced).toHaveAttribute('aria-expanded', 'true')
  await drawer.getByLabel('sys 账号', { exact: true }).fill('synthetic-sys')
  stage = '收起高级设置'
  await advanced.click()
  await expect(drawer.getByLabel('sys 密码', { exact: true })).not.toBeVisible()
  await drawer.getByLabel('主机 IP/域名', { exact: true }).fill('192.0.2.77')
  await drawer.getByLabel('租户名', { exact: true }).fill('synthetic-tenant')
  await drawer.getByLabel('数据库用户名', { exact: true }).fill('synthetic-user')
  await drawer.getByLabel('数据库密码', { exact: true }).fill('synthetic-password-fixture')
  await drawer.locator('.orch-source-metadata .ant-select-selector').click()
  await page.locator('.ant-select-dropdown:visible .ant-select-item-option').filter({ hasText: '测试' }).click()
  stage = '校验定位'
  await drawer.getByRole('button', { name: '确定', exact: true }).click()
  await expect(advanced).toHaveAttribute('aria-expanded', 'true')
  await expect(drawer.getByLabel('sys 密码', { exact: true })).toBeFocused()
  expect(errors).toEqual([])
})

test('服务端分页、筛选和迟到响应不会被 Table 状态重解释', async ({ page }) => {
  const urls: URL[] = []
  let releaseSlow: (() => void) | undefined
  await page.route('**/api/v1/data-sources?*', async route => {
    const url = new URL(route.request().url()); urls.push(url)
    const keyword = url.searchParams.get('keyword')
    if (keyword === 'slow') await new Promise<void>(resolve => { releaseSlow = resolve })
    await route.fulfill({ json: { items: [{ ...DATA_SOURCE_UI_FIXTURES[0], displayName: keyword || (url.searchParams.has('cursor') ? '第二页事实' : '首页事实') }], total: 20, nextCursor: url.searchParams.has('cursor') ? '' : 'synthetic-next' } })
  })
  await page.goto('/data-sources')
  await expect(page.getByRole('button', { name: '首页事实', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '下一页', exact: true }).click()
  await expect(page.getByRole('button', { name: '第二页事实', exact: true })).toBeVisible()
  expect(urls.at(-1)?.searchParams.get('cursor')).toBe('synthetic-next')
  await page.getByRole('textbox', { name: '搜索数据源' }).fill('slow')
  await expect.poll(() => Boolean(releaseSlow)).toBe(true)
  await page.getByRole('textbox', { name: '搜索数据源' }).fill('latest')
  await expect(page.getByRole('button', { name: 'latest', exact: true })).toBeVisible()
  expect(urls.at(-1)?.searchParams.has('cursor')).toBe(false)
  releaseSlow!()
  await expect(page.getByRole('button', { name: 'slow', exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'latest', exact: true })).toBeVisible()
})

test('删除安全确认与服务端并发资格复验，取消不发请求', async ({ page }) => {
  let deletes = 0
  let revision = ''
  const item = { ...DATA_SOURCE_UI_FIXTURES[0], displayName: '合成可删除数据源', lifecycleEligibility: { enable: { allowed: false }, disable: { allowed: true }, delete: { allowed: true }, archive: { allowed: false } } }
  await page.route('**/api/v1/**', route => {
    if (route.request().method() === 'DELETE') {
      deletes++; revision = route.request().headers()['if-match'] ?? ''
      return route.fulfill({ status: 409, json: { code: 'UNFINISHED_TASKS_EXIST' } })
    }
    return route.fulfill({ json: { items: [item], total: 1, nextCursor: '' } })
  })
  await page.goto('/data-sources')
  const trigger = page.getByRole('button', { name: '合成可删除数据源 的操作' })
  await trigger.click()
  await expect(page.getByRole('menuitem')).toHaveCount(2)
  await page.getByRole('menuitem', { name: '删除', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '删除数据源' })
  await expect(dialog.getByRole('button', { name: '取消', exact: true })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(dialog).not.toBeVisible()
  expect(deletes).toBe(0)
  await trigger.click()
  await page.getByRole('menuitem', { name: '删除', exact: true }).click()
  await dialog.getByRole('button', { name: '删除', exact: true }).click()
  await expect.poll(() => deletes).toBe(1)
  expect(revision).toContain('101')
  await expect(page.getByRole('button', { name: '合成可删除数据源', exact: true })).toBeVisible()
  await expect(page.getByRole('alert')).toContainText('操作未完成')
})

test('数据源命名保存清理秘密，测试异步事实与可用状态独立', async ({ page }) => {
  await page.route('**/api/v1/**', route => route.abort())
  await page.goto('/data-sources?uiFixture=data-sources')
  await page.getByRole('button', { name: '新建数据源', exact: true }).click()
  await page.getByRole('menuitem', { name: 'OceanBase MySQL', exact: true }).click()
  let drawer = page.getByRole('dialog', { name: '新建数据源', exact: true })
  await drawer.getByLabel('主机 IP/域名', { exact: true }).fill('192.0.2.77')
  await drawer.getByLabel('租户名', { exact: true }).fill('synthetic-tenant')
  await drawer.getByLabel('数据库用户名', { exact: true }).fill('synthetic-user')
  await drawer.getByLabel('数据库密码', { exact: true }).fill('synthetic-password-fixture')
  await drawer.locator('.orch-source-metadata .ant-select-selector').click()
  await page.locator('.ant-select-dropdown:visible .ant-select-item-option').filter({ hasText: '测试' }).click()
  await drawer.getByRole('button', { name: '确定', exact: true }).click()
  const naming = page.getByRole('dialog', { name: '填写数据源名称' })
  await naming.getByLabel('数据源名称', { exact: true }).fill('合成新建数据源')
  await naming.getByRole('button', { name: '保存', exact: true }).click()
  await expect(naming).not.toBeVisible()
  drawer = page.getByRole('dialog', { name: '编辑数据源', exact: true })
  await expect(drawer.getByLabel('数据库密码', { exact: true })).toHaveValue('')
  await drawer.getByRole('button', { name: '测试连接', exact: true }).click()
  await drawer.getByRole('combobox', { name: /执行节点/ }).focus()
  await page.keyboard.press('ArrowDown')
  await page.getByText('Visual validation runtime · WINDOWS_AMD64', { exact: true }).click()
  await drawer.getByRole('button', { name: '开始测试', exact: true }).click()
  await expect(drawer.getByText('等待执行节点回写结果', { exact: true })).toBeVisible()
  await expect(drawer.getByText('合成验证结果', { exact: true })).toBeVisible({ timeout: 10000 })
  const history = drawer.getByRole('button', { name: '查看验证记录', exact: true })
  await history.focus()
  await page.keyboard.press('Enter')
  await expect(history).toHaveAttribute('aria-expanded', 'true')
  await expect(drawer.getByText('结果代码', { exact: true })).toBeVisible()
  await drawer.getByRole('button', { name: '取消', exact: true }).click()
  await expect(page.getByRole('switch', { name: '合成新建数据源 的可用状态' })).not.toBeChecked()
})

test('冻结控件几何、长文本与删除禁用原因可访问', async ({ page }) => {
  await page.route('**/api/v1/**', route => route.abort())
  await page.goto('/data-sources?uiFixture=data-sources')
  await expect(page.getByRole('table')).toBeVisible()
  expect((await page.getByRole('button', { name: '新建数据源', exact: true }).boundingBox())!.height).toBe(36)
  expect(await page.getByRole('button', { name: '新建数据源', exact: true }).evaluate(el => getComputedStyle(el).borderRadius)).toBe('6px')
  expect((await page.getByRole('columnheader', { name: '数据源', exact: true }).boundingBox())!.height).toBe(36)
  expect((await page.getByRole('switch').first().boundingBox())!.height).toBe(22)
  await page.getByRole('button', { name: 'Production finance reporting 的操作' }).click()
  await expect(page.getByRole('menuitem', { name: /删除/ })).toHaveAttribute('aria-disabled', 'true')
  await expect(page.getByText('存在未完成任务，请等待任务结束后删除。', { exact: true })).toBeVisible()
})

test('长名称和端点保留完整可访问事实，横滚限定于工作面', async ({ page }) => {
  const longName = '合成长名称'.repeat(24)
  const host = `${'synthetic-'.repeat(20)}.example.invalid`
  await page.route('**/api/v1/**', route => route.fulfill({ json: { items: [{ ...DATA_SOURCE_UI_FIXTURES[0], displayName: longName, host }], total: 1, nextCursor: '' } }))
  await page.setViewportSize({ width: 1280, height: 720 })
  await page.goto('/data-sources')
  await expect(page.getByRole('button', { name: longName, exact: true })).toHaveAttribute('title', longName)
  await expect(page.getByTitle(`${host}:2883`, { exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('行菜单可由键盘打开、导航并通过 ESC 返回触发器', async ({ page }) => {
  await page.route('**/api/v1/**', route => route.abort())
  await page.goto('/data-sources?uiFixture=data-sources')
  const trigger = page.getByRole('button', { name: 'Production finance reporting 的操作' })
  await trigger.focus()
  await page.keyboard.press('ArrowDown')
  await expect(page.getByRole('menuitem', { name: '编辑', exact: true })).toBeFocused()
  await page.keyboard.press('ArrowDown')
  await page.keyboard.press('Escape')
  await expect(trigger).toBeFocused()
  await expect(page.getByRole('menuitem')).toHaveCount(0)
})

test('行菜单再次打开仍可导航到可用删除动作', async ({ page }) => {
  const item = { ...DATA_SOURCE_UI_FIXTURES[0], displayName: '合成菜单数据源', lifecycleEligibility: { enable: { allowed: false }, disable: { allowed: true }, delete: { allowed: true }, archive: { allowed: false } } }
  await page.route('**/api/v1/**', route => route.fulfill({ json: { items: [item], total: 1, nextCursor: '' } }))
  await page.goto('/data-sources')
  const trigger = page.getByRole('button', { name: '合成菜单数据源 的操作' })
  for (let attempt = 0; attempt < 2; attempt++) {
    await trigger.focus()
    await page.keyboard.press('ArrowDown')
    await expect(page.getByRole('menuitem', { name: '编辑', exact: true })).toBeFocused()
    await page.keyboard.press('ArrowDown')
    await expect(page.getByRole('menuitem', { name: '删除', exact: true })).toBeFocused()
    await page.keyboard.press('ArrowUp')
    await expect(page.getByRole('menuitem', { name: '编辑', exact: true })).toBeFocused()
    await page.keyboard.press('End')
    await expect(page.getByRole('menuitem', { name: '删除', exact: true })).toBeFocused()
    await page.keyboard.press('Home')
    await expect(page.getByRole('menuitem', { name: '编辑', exact: true })).toBeFocused()
    await page.keyboard.press('Escape')
    await expect(trigger).toBeFocused()
  }
})

test('加载、空结果与错误重试保持独立状态', async ({ page }) => {
  let release: (() => void) | undefined
  let attempts = 0
  await page.route('**/api/v1/data-sources?*', async route => {
    attempts++
    if (attempts === 1) {
      await new Promise<void>(resolve => { release = resolve })
      return route.fulfill({ status: 500, json: { code: 'INTERNAL_ERROR' } })
    }
    return route.fulfill({ json: { items: [], total: 0, nextCursor: '' } })
  })
  await page.goto('/data-sources')
  await expect(page.getByRole('status', { name: '正在加载数据源' })).toBeVisible()
  await expect(page.getByRole('button', { name: '刷新数据源', exact: true })).toBeDisabled()
  await expect(page.getByRole('heading', { name: '尚未创建数据源' })).toHaveCount(0)
  release!()
  await expect(page.getByRole('alert')).toContainText('暂时无法读取数据源')
  await page.getByRole('button', { name: '重新加载', exact: true }).click()
  await expect(page.getByRole('heading', { name: '尚未创建数据源' })).toBeVisible()
  await expect(page.getByRole('alert')).toHaveCount(0)
})
