import type { UnwrapNestedRefs } from 'vue'
import type { ExportWizard } from './useExportWizard'

// 各步骤只声明自己消费的字段与意图；所有字段仍引用向导的唯一表单。
export type ExportSourceStepModel = Pick<UnwrapNestedRefs<ExportWizard>, 'sourceKeyword' | 'fieldPrefix' | 'sourceEnvironment' | 'sourceLoadFailure' | 'loadSources' | 'loadingSources' | 'eligibleSources' | 'sources' | 'router' | 'visibleSources' | 'selectedDataSourceID' | 'derivedDraftBindingLocked' | 'selectedSource'>

export type ExportObjectsStepModel = Pick<UnwrapNestedRefs<ExportWizard>, 'exportMode' | 'scopeKind' | 'contentKind' | 'fieldPrefix' | 'nodeLoadFailure' | 'loadingNodes' | 'selectedNodeID' | 'derivedDraftBindingLocked' | 'nodes' | 'attemptedStep' | 'database' | 'selectedSource' | 'databaseDropdownOpen' | 'databaseCatalogLoading' | 'onDatabaseDropdownVisibleChange' | 'scheduleDatabaseCatalog' | 'selectDatabaseOption' | 'databaseOptions' | 'databaseCatalogFailure' | 'databaseCatalogLoaded' | 'manualDatabaseInput' | 'manualDatabaseError' | 'manualDatabaseOpen' | 'loadDatabaseCatalog' | 'databaseCatalogTruncated' | 'querySql' | 'queryResultLimit' | 'objectInputMessage' | 'confirmManualDatabase' | 'enteredObjectCount' | 'allSelectedObjects' | 'candidateTotalCount' | 'candidateObjectKeyword' | 'loadCatalog' | 'catalogLoading' | 'catalogKeywordTooLong' | 'catalogFailure' | 'catalogTruncated' | 'visibleObjectCategories' | 'objectType' | 'candidateGroupExpanded' | 'chooseObjectCategory' | 'selectableCategoryNames' | 'categorySelectedCount' | 'toggleCategorySelection' | 'catalogCount' | 'candidateObjectNames' | 'catalogLoaded' | 'visibleCandidateObjectNames' | 'objectNames' | 'toggleCandidate' | 'clearObjectNameRows' | 'selectedObjectKeyword' | 'visibleSelectedGroups' | 'selectedGroupExpanded' | 'clearObjectCategory' | 'removeObjectNameRow' | 'objectAdvancedCount' | 'dataOptionsActive' | 'excludeTablesSupported' | 'excludeTablesText' | 'includeColumnNames' | 'excludeColumnNames' | 'excludeDataTypes' | 'whereSupported' | 'where' | 'partitionSupported' | 'partition' | 'migrateLegacyQuery'>

export type ExportFormatStepModel = Pick<UnwrapNestedRefs<ExportWizard>, 'blockSizeChoices' | 'formatChangeNotice' | 'contentKind' | 'dataOptionsActive' | 'fieldPrefix' | 'formatKind' | 'fileEncoding' | 'ordinaryFormat' | 'draftValidationMessage' | 'columnSeparator' | 'columnSplitter' | 'columnQuote' | 'lineSeparator' | 'columnQuoteMode' | 'nullString' | 'escapeCharacter' | 'dropObject' | 'retainSchema' | 'compactSchemaSupported' | 'compactSchema' | 'scopeKind' | 'querySql' | 'snapshot' | 'flashbackScn' | 'flashbackTimestamp' | 'tableOnlySelection' | 'excludeVirtualColumns' | 'selectedSource' | 'skipHeader' | 'withTrim' | 'trailDelimiter' | 'removeNewline' | 'noNestedDir' | 'retainEmptyFiles' | 'formatAdvancedCount' | 'timestampFormatsSupported' | 'datetimeValueFormat' | 'dateValueFormat' | 'splitUnit' | 'changeSplitUnit' | 'attemptedStep' | 'blockSize' | 'splitThreshold' | 'compress' | 'compressionAlgo' | 'compressionLevel'>

export type ExportOutputStepModel = Pick<UnwrapNestedRefs<ExportWizard>, 'draftNotice' | 'attemptedStep' | 'selectedNodeID' | 'nodeLoadFailure' | 'loadNodeCandidates' | 'loadingNodes' | 'selectedNode' | 'derivedDraftBindingLocked' | 'moveToStep' | 'outputKind' | 'storageBucket' | 'storagePath' | 'storageEndpoint' | 'storageRegion' | 'fieldPrefix' | 'storageCredentialLoadFailure' | 'loadStorageCredentials' | 'loadingStorageCredentials' | 'storageCredentialID' | 'matchingStorageCredentials' | 'filePath' | 'outputPathPlaceholder' | 'logPath' | 'skipCheckDir' | 'executionAdvancedCount' | 'dataOptionsActive' | 'maxFileSize' | 'thread' | 'pageSize' | 'parallelMacro' | 'selectedSource' | 'fetchSize' | 'jvmMemory' | 'tmpPath' | 'draftFailure'>

export type ExportReviewStepModel = Pick<UnwrapNestedRefs<ExportWizard>, 'draftNotice' | 'activePrecheck' | 'loadingDraft' | 'draftLoadFailure' | 'loadCreatedDraft' | 'displayedSource' | 'currentDraft' | 'displayedDraftConfig' | 'draftScopeSummary' | 'draftContentLabel' | 'draftDeliverySummary' | 'draftFileSummary' | 'displayedNode' | 'storageOutput' | 'precheckFailure' | 'precheckRunning' | 'blockingPrecheckRows' | 'precheckRows' | 'commandPreview' | 'copyCommand' | 'previewingCommand' | 'commandPreviewFailure' | 'loadCommandPreview' | 'copyNotice' | 'submissionFailure'>

export type ExportSummaryModel = Pick<UnwrapNestedRefs<ExportWizard>, 'titles' | 'activeStep' | 'displayedSource' | 'displayedDraftConfig' | 'draftScopeSummary' | 'database' | 'scopeKind' | 'contentKind' | 'formatKind' | 'displayedNode' | 'activePrecheck'>

export type ExportSubmitConfirmationModel = Pick<UnwrapNestedRefs<ExportWizard>, 'submitConfirmationOpen' | 'submitting' | 'closeSubmitConfirmation' | 'submitCancelID' | 'confirmSubmitTask' | 'displayedSource' | 'draftScopeSummary' | 'displayedDraftConfig' | 'dropObject' | 'removeNewline' | 'submissionFailure'>
